In [2]:
import numpy as np
np.zeros((10,))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
sum(np.zeros(10))

0.0

In [5]:
a = np.zeros((10,))
a.shape()

TypeError: 'tuple' object is not callable

In [6]:
a.shape

(10,)

In [7]:
b = np.ones(10)
b.shape

(10,)

In [8]:
 policy_table = np.random.choice(5,[64, ])

In [9]:
print(policy_table)

[4 2 0 2 2 2 3 3 2 1 0 3 0 2 4 1 2 3 4 3 2 1 0 1 3 3 2 4 2 1 0 2 4 0 3 3 0
 0 4 1 0 0 3 1 0 4 2 3 4 1 1 0 3 4 0 0 1 2 0 2 0 1 3 3]


In [10]:
policy_table.shape

(64,)

In [3]:
np.zeros(5,5)

TypeError: data type not understood

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.zeros((64,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [7]:
import gym
env = gym.make("FrozenLake8x8-v0")
obs = env.reset()
print(obs)

0
